parameters: {}
environment: 
  LOG_DESTINATIONS: '[{"papertrail":{"token":"mldzRwtv6VqKe4zLrskkK63idDXa"}}]'
  NOTION_TOKEN : 'secret_JWMvK7TSIwPKmp4DbHN8gwZFfBWujjbC8xYiHhVF1Ak'
  WEBFLOW_API_TOKEN : '5d080ec8b13e7f6bc1bafd515d302606a08858b5dcfab7850537620dc4b49302'
  DATABASE_URL: 'mongodb+srv://ace:PIAbLGXXP4BP7AaC@cluster0.esdgm.mongodb.net/layers-ajay'
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}

